### ISSUE TITLE
500 Internal Server Error - ⨯ Error: Could not locate the bindings file.

### ISSUE THREAD

**Issue by kirincorleone** [hoarder-app/hoarder#1107]
Hi,

I am unable to log into hoarder. I am getting 500 | Internal Server Error upon logging in.

These are the logs of Hoarder Container:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service init-db-migration: starting
Running db migration script
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-db-migration successfully started
s6-rc: info: service svc-workers: starting
s6-rc: info: service svc-web: starting
s6-rc: info: service svc-workers successfully started
s6-rc: info: service svc-web successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
  ▲ Next.js 14.2.21
  - Local:        http://localhost:3000
  - Network:      http://0.0.0.0:3000/
 ✓ Starting...
 ✓ Ready in 773ms
> @hoarder/workers@0.1.0 start:prod /app/apps/workers
> tsx index.ts
2025-03-10T13:57:43.719Z info: Workers version: nightly
2025-03-10T13:57:43.798Z info: [crawler] Loading adblocker ...
2025-03-10T13:57:46.958Z info: [Crawler] Connecting to existing browser instance: http://chrome:9222
2025-03-10T13:57:46.960Z info: [Crawler] Successfully resolved IP address, new address: http://172.24.0.2:9222/
2025-03-10T13:57:47.153Z info: Starting crawler worker ...
2025-03-10T13:57:47.154Z info: Starting inference worker ...
2025-03-10T13:57:47.154Z info: Starting search indexing worker ...
2025-03-10T13:57:47.155Z info: Starting tidy assets worker ...
2025-03-10T13:57:47.155Z info: Starting video worker ...
2025-03-10T13:57:47.156Z info: Starting feed worker ...
2025-03-10T13:57:47.156Z info: Starting asset preprocessing worker ...
2025-03-10T13:57:47.157Z info: Starting webhook worker ...
[next-auth][warn][NEXTAUTH_URL] 
https://next-auth.js.org/warnings#nextauth_url
[next-auth][error][JWT_SESSION_ERROR] 
https://next-auth.js.org/errors#jwt_session_error decryption operation failed {
[next-auth][error][JWT_SESSION_ERROR] 
https://next-auth.js.org/errors#jwt_session_error decryption operation failed {
[next-auth][error][JWT_SESSION_ERROR] 
https://next-auth.js.org/errors#jwt_session_error decryption operation failed {
  message: 'decryption operation failed',
  stack: 'a: decryption operation failed\n' +
    '    at /app/apps/web/.next/server/chunks/8195.js:27:89692\n' +
    '    at t.default (/app/apps/web/.next/server/chunks/8195.js:27:89719)\n' +
    '    at p (/app/apps/web/.next/server/chunks/8195.js:27:33504)\n' +
    '    at async o (/app/apps/web/.next/server/chunks/8195.js:27:29176)\n' +
    '    at async o (/app/apps/web/.next/server/chunks/8195.js:27:56146)\n' +
    '    at async Object.h [as decode] (/app/apps/web/.next/server/chunks/8195.js:27:17269)\n' +
    '    at async Object.n (/app/apps/web/.next/server/chunks/8195.js:27:6864)\n' +
    '    at async m (/app/apps/web/.next/server/chunks/8195.js:3:22504)\n' +
    '    at async p (/app/apps/web/.next/server/app/signin/page.js:1:12349)',
  name: 'a'
}
[next-auth][error][JWT_SESSION_ERROR] 
https://next-auth.js.org/errors#jwt_session_error decryption operation failed {
 ⨯ Error: Could not locate the bindings file. Tried:
 → /app/apps/web/.next/build/better_sqlite3.node
 → /app/apps/web/.next/build/Debug/better_sqlite3.node
 → /app/apps/web/.next/build/Release/better_sqlite3.node
 → /app/apps/web/.next/out/Debug/better_sqlite3.node
 → /app/apps/web/.next/Debug/better_sqlite3.node
 → /app/apps/web/.next/out/Release/better_sqlite3.node
 → /app/apps/web/.next/Release/better_sqlite3.node
    at new o (/app/apps/web/.next/server/chunks/632.js:4:45182)
    at t2 (/app/apps/web/.next/server/chunks/632.js:19:20729)
    at 40947 (/app/apps/web/.next/server/chunks/9415.js:1:9685)
    at t (/app/apps/web/.next/server/webpack-runtime.js:1:143)
    at 36815 (/app/apps/web/.next/server/chunks/9415.js:1:347)
    at 25729 (/app/apps/web/.next/server/app/dashboard/bookmarks/page.js:1:5531)
    at t (/app/apps/web/.next/server/webpack-runtime.js:1:143)
    at 99990 (/app/apps/web/.next/server/app/dashboard/bookmarks/page.js:1:5334) {
    '/app/apps/web/.next/build/Release/better_sqlite3.node',
    '/app/apps/web/.next/out/Debug/better_sqlite3.node',
    '/app/apps/web/.next/Debug/better_sqlite3.node',
    '/app/apps/web/.next/compiled/22.14.0/linux/x64/better_sqlite3.node',
    '/app/apps/web/.next/addon-build/release/install-root/better_sqlite3.node',
    '/app/apps/web/.next/addon-build/debug/install-root/better_sqlite3.node',
    '/app/apps/web/.next/addon-build/default/install-root/better_sqlite3.node',
```

These are the logs for Chrome: 

```
[0310/135734.611482:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[0310/135734.618800:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[0310/135734.620206:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[0310/135734.624518:WARNING:dns_config_service_linux.cc(427)] Failed to read DnsConfig.
[0310/135734.980550:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping mandatory platform policies because no policy file was found at: /etc/chromium/policies/managed
[0310/135734.981845:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping recommended platform policies because no policy file was found at: /etc/chromium/policies/recommended
DevTools listening on ws://0.0.0.0:9222/devtools/browser/0da6b881-5acc-4c2c-bda3-97e21a1f9d16
[0310/135734.994046:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
[0310/135735.093855:WARNING:dns_config_service_linux.cc(427)] Failed to read DnsConfig.
[0310/135735.111380:WARNING:sandbox_linux.cc(418)] InitializeSandbox() called with multiple threads in process gpu-process.
```

These are my compose files:

```
web:
    image: ghcr.io/hoarder-app/hoarder:latest
    container_name: Hoarder-WEB
    restart: on-failure:5
    volumes:
      - /path/data:/data:rw
    ports:
      - 3022:3000
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - hoardernet
    environment:
      #REDIS_HOST: redis
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data
      NEXTAUTH_SECRET: 123
      MEILI_MASTER_KEY: 123
      OLLAMA_BASE_URL: http://ollama.xyz
```

```
chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    container_name: Hoarder-CHROME
    restart: on-failure:5
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - hoardernet
    command:
      - --no-sandbox
      - --disable-gpu
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
```

```
meilisearch:
    image: getmeili/meilisearch:v1.6.2
    container_name: Hoarder-MEILI
    restart: unless-stopped
    volumes:
      - /path/meili:/meili_data:rw
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - hoardernet
    environment:
     MEILI_MASTER_KEY: 123
     MEILI_NO_ANALYTICS: true
```
