### ISSUE TITLE
DrizzleError after clean(?) install

### ISSUE THREAD

**Issue by ggstrader** [hoarder-app/hoarder#1112]
Apologies I'm not sure how to troubleshoot this, I'm just getting started with hoarder and don't see anything related in the docs or issues.

I successfully installed hoarder on my Ubuntu VM and got it working with OpenAI and Ollama. However I had to uninstall it momentarily. Upon reinstallation using the same .env and docker-compose files, I can no longer connect to the web interface. I tried clearing browser cache and rebooting my laptop and VM. `docker ps` shows the web container as unhealthy, and the console output of `docker-compose up` shows:
```
web_1          | /db_migrations/index.js:7331
web_1          |       throw new DrizzleError({ cause: err, message: `Failed to run the query '${staticQuery.sql}'` });
web_1          |       ^
web_1          | 
web_1          | DrizzleError: Failed to run the query '
web_1          |                        CREATE TABLE IF NOT EXISTS "__drizzle_migrations" (
web_1          |                                id SERIAL PRIMARY KEY,
web_1          |                                hash text NOT NULL,
web_1          |                                created_at numeric
web_1          |                        )
web_1          |                '
web_1          |     at BetterSQLiteSession.run (/db_migrations/index.js:7331:13)
web_1          |     at SQLiteSyncDialect.migrate (/db_migrations/index.js:5463:13)
web_1          |     ... 6 lines matching cause stack trace ...
web_1          |     at Module.load (node:internal/modules/cjs/loader:1313:32)
web_1          |     at Function._load (node:internal/modules/cjs/loader:1123:12) {
web_1          |   cause: SqliteError: database is locked
web_1          |       at PreparedQuery.run (/db_migrations/index.js:7440:22)
web_1          |       at BetterSQLiteSession.run (/db_migrations/index.js:7329:74)
web_1          |       at SQLiteSyncDialect.migrate (/db_migrations/index.js:5463:13)
web_1          |       at migrator_migrate (/db_migrations/index.js:12511:14)
web_1          |       at /db_migrations/index.js:12518:1
web_1          |       at /db_migrations/index.js:12520:3
web_1          |       at Object.<anonymous> (/db_migrations/index.js:12523:12)
web_1          |       at Module._compile (node:internal/modules/cjs/loader:1562:14)
web_1          |       at Object..js (node:internal/modules/cjs/loader:1699:10)
web_1          |       at Module.load (node:internal/modules/cjs/loader:1313:32) {
web_1          |     code: 'SQLITE_BUSY'
web_1          |   }
web_1          | }
web_1          | 
web_1          | Node.js v22.13.1
web_1          | s6-rc: warning: unable to start service init-db-migration: command exited 1
```

I thought I may have screwed up something docker/hoarder related so I decided the simplest fix would be to start fresh and remove hoarder and docker completely using:
```sh
cd hoarder/
docker stop $(docker ps -aq)
docker rm -f $(docker ps -aq)
docker system prune -a --volumes
sudo rm -rf /s/backup/hoarder/data/
sudo rm -rf meilisearch/
sudo apt remove --purge docker docker-engine docker.io containerd runc docker-compose-plugin -y
sudo apt remove --purge docker-ce docker-ce-cli docker-ce-rootless-extras docker-buildx-plugin -y
sudo rm -rf /var/lib/docker
sudo rm -rf /var/lib/containerd
sudo rm -rf /etc/docker
sudo rm -rf ~/.docker
sudo apt autoremove -y
```

And installed again using:
```sh
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh
sudo apt install docker-compose-plugin -y
sudo systemctl enable --now docker
```

My docker-compose:
```yaml
version: "3.8"
services:
  web:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - /s/backup/hoarder/data:/data
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      # OPENAI_API_KEY: ...

      # You almost never want to change the value of the DATA_DIR variable.
      # If you want to mount a custom directory, change the volume mapping above instead.
      DATA_DIR: /data # DON'T CHANGE THIS
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - /home/ggs/hoarder/meilisearch:/meili_data

volumes:
  meilisearch:
  data:
```

My .env:
```sh
HOARDER_VERSION=0.22.0
NEXTAUTH_SECRET=#
MEILI_MASTER_KEY=#
NEXTAUTH_URL=http://localhost:3000
OLLAMA_BASE_URL=http://192.168.1.16:11434
INFERENCE_TEXT_MODEL=nchapman/gemma-2-9b-it-abliterated
INFERENCE_IMAGE_MODEL=llava
INFERENCE_CONTEXT_LENGTH=2048
OLLAMA_KEEP_ALIVE=15m
```

I'm not sure what could've gone wrong and am not so sure I didn't see the same DrizzleError the first time I installed successfully so I'm not really sure how to troubleshoot this. Any help appreciated.
