### ISSUE TITLE
Feature request: provide a VNC client to log in user websites on the Hoarder puppeteer instance

### ISSUE THREAD

**Issue by maelp** [hoarder-app/hoarder#1166]
Would be really nice to either share Chrome cookies with the backend, or let the user connect through VNC (or whatever) to the backend puppeteer instance, in order to login to the websites that requires it (NYTimes, etc)

Check https://github.com/franciskim/docker-ubuntu-novnc-puppeteer and https://github.com/m1k1o/neko and https://novnc.com/info.html

**Comment by maelp** [comment]
Also https://guacamole.apache.org/

**Comment by maelp** [comment]
Actually perhaps the easiest way would be to allow us to "mount" the folder with puppeteer cookies somewhere, then we could (for those who want) install a lightweight VNC server alongside hoarder, sharing the same cookies, use that to login with a browser (or copy our local chrome cookies there), and then hoarder should share the cookies and be automatically logged in?

**Comment by maelp** [comment]
A few ideas from ChatGPT on that setup: https://chatgpt.com/share/67e3c16e-81d8-800b-b248-7af64a81cdf6

**Comment by maelp** [comment]
Note that an easier way might be to just add a "share cookies for this tab with backend" feature on the Chrome extension, see https://github.com/hoarder-app/hoarder/issues/1167

**Comment by SettingDust** [comment]
According to https://github.com/ArchiveBox/ArchiveBox/wiki/Chromium-Install#setting-up-a-chromium-user-profile
Looks like this is the easiest way to resolve the cookies issue. Accept an env for the chrome profile. Add Chromium to the dockerfile. 
The users can use novnc like how ArchiveBox did that.

**Comment by maelp** [comment]
Would be perfect! Although I think in terms of security it's no better than just sharing the cookies to the backend through the extension which might be a bit more user-friendly (no need for a big VNC setup), but as you guys prefer

**Comment by SettingDust** [comment]
> Would be perfect! Although I think in terms of security it's no better than just sharing the cookies to the backend through the extension which might be a bit more user-friendly (no need for a big VNC setup), but as you guys prefer

Share the cookies need more coding in my mind. It's neat anyway

**Comment by maelp** [comment]
I think the cookie solution is quite easy no? From what I've seen, browser extensions have a simple API to access cookies like `currentTab.getCookies()` and then you just send `JSON.stringify(cookies)` to the backend, which stores them on a file on disk and ask Puppeteer to load them, no?

**Comment by maelp** [comment]
Example implementation of no-vnc setup https://github.com/onkernel/kernel-images/tree/main/unikernels/unikraft-cu

**Comment by maelp** [comment]
Okay we can start with something like this for instance (check https://github.com/maelp/docker-vnc-chromium)

```yml
  chrome-desktop:
    image: maelp/docker-vnc-chromium:latest
    platform: linux/amd64
    ports:
      - "5800:5800"
    environment:
      - VNC_PASSWORD=my-secure-vnc-password
      - WEB_AUTHENTICATION=1
      - WEB_AUTHENTICATION_USERNAME=admin
      - WEB_AUTHENTICATION_PASSWORD=my-secure-web-password
      - SECURE_CONNECTION=1
    volumes:
      - /tmp/karakeep/vnc-chrome-config:/config:rw
    restart: unless-stopped
```

**Comment by maelp** [comment]
This allows to login to some websites

**Comment by maelp** [comment]
I still have issues scraping NYtimes (even though I logged in) and Youtube though...

![Image](https://github.com/user-attachments/assets/48bc677f-a655-46c1-a752-d4af3e738a32)

![Image](https://github.com/user-attachments/assets/c1eea37b-6b9e-4407-84d2-3a437e15bce5) for this page https://www.youtube.com/watch?v=aRPXsnSmnvc

**Comment by maelp** [comment]
For now I'm using this config in my Dokploy setup

```yaml
  chrome-vnc:
    image: maelp/docker-vnc-chromium:1.5
    ports:
      - "5800:5800"
    environment:
      - VNC_PASSWORD=my-super-secret-strong-password-horse
      - VNC_RESOLUTION=1920x1080
    volumes:
      - /mnt/data/karakeep/chrome-vnc-userdata:/config/userdata:rw
      - /opt/karakeep/cache:/config/cache:rw
    restart: unless-stopped
```

It allows me to connect through VNC, but it seems that my cookies are not necessarily found by puppeteer for now, so there might be other stuff to find

**Comment by MohamedBassem** [comment]
@maelpThis looks promising. Puppeteer currently (given the way it's set up), doesn't have much of a say in the cookies.  Here's how I think you can make it work. Can you try mounting:

```
/mnt/data/karakeep/chrome-vnc-userdata:/config/userdata:rw
```

to the chrome container as well, and change the flags of the chrome container to include:

```
--user-data-dir=/config/userdata
```

?

Let me know if this works.

**Comment by maelp** [comment]
So you think we would need to use both "chrome" and "chrome-vnc" ? I would have thought the chome-vnc docker that I did would replace the other chrome no? I will try though

**Comment by maelp** [comment]
Okay so I added back the original "chrome" container (from my Dokploy config, might be similar to the one on your doc) and mounted those volumes, and kept the "http://chrome:9222" for the BROWSER_URL of the Karakeep API

```
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:124
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
      - --user-data-dir=/config/userdata
    volumes:
      - /mnt/data/karakeep/chrome-vnc-userdata:/config/userdata:rw
  chrome-vnc:
    image: maelp/docker-vnc-chromium:1.5
    ports:
      - "5800:5800"
    environment:
      - VNC_PASSWORD=somepassword
      - VNC_RESOLUTION=1920x1080
    volumes:
      - /mnt/data/karakeep/chrome-vnc-userdata:/config/userdata:rw
      - /opt/karakeep/cache:/config/cache:rw
    restart: unless-stopped
```
