### ISSUE TITLE
How to verify hoarder app is working with the local ollama 

### ISSUE THREAD

**Issue by lihw** [hoarder-app/hoarder#185]
I modify the docker-compose.yml a bit to make hoarder use local ollama inference. Here is the modified yml file.

```
version: "3.8"
services:
  web:
    image: ghcr.io/hoarder-app/hoarder-web:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - data:/data
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      MEILI_ADDR: http://meilisearch:7700
      DATA_DIR: /data
  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis:/data
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.6
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data
  ollama:
    hostname: ollama-container
    image: ollama/ollama:0.1.39-rocm
    restart: unless-stopped
    volumes:
      - ollama:/data/ollama
    ports:
      - 11434:11434
    env_file:
      - .env
  workers:
    image: ghcr.io/hoarder-app/hoarder-workers:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - data:/data
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data
      OLLAMA_BASE_URL: http://ollama-container:11434
      INFERENCE_TEXT_MODEL: llama3
      # OPENAI_API_KEY: ...
    depends_on:
      web:
        condition: service_started

volumes:
  redis:
  meilisearch:
  ollama:
  data:
```

I entered the hoarder worker container and checked if `ollama-container:13414` is connectable. Yes. But when I open the hoader webpage, it seems no inference is working. I am wondering where hoarder log is. How can I verify that the hoarder app is already connecting to local inference service.
