### ISSUE TITLE
 [Crawler] Failed to connect to the browser instance, will retry in 5 secs

### ISSUE THREAD

**Issue by XiaoSiHwang** [hoarder-app/hoarder#193]
Hoarder crawler doesnt wrok
[hoarder-workers](http://192.168.0.11:9000/#!/2/docker/containers/2767f8c96c171e6ccfbf63f3be44ba65360f9881c4e7af46119ea58771860abd):
2024-06-04T16:07:30.401Z info: [Crawler] Successfully resolved IP address, new address: http://172.31.0.4:9333/
2024-06-04T16:07:31.931Z error: [Crawler] Failed to connect to the browser instance, will retry in 5 secs
2024-06-04T16:07:36.932Z info: [Crawler] Connecting to existing browser instance: http://chrome:9333
2024-06-04T16:07:36.933Z info: [Crawler] Successfully resolved IP address, new address: http://172.31.0.4:9333/
2024-06-04T16:07:38.500Z error: [Crawler] Failed to connect to the browser instance, will retry in 5 secs
2024-06-04T16:07:43.501Z info: [Crawler] Connecting to existing browser instance: http://chrome:9333
2024-06-04T16:07:43.502Z info: [Crawler] Successfully resolved IP address, new address: http://172.31.0.4:9333/
2024-06-04T16:07:45.073Z error: [Crawler] Failed to connect to the browser instance, will retry in 5 secs
2024-06-04T16:07:50.075Z info: [Crawler] Connecting to existing browser instance: http://chrome:9333
2024-06-04T16:07:50.075Z info: [Crawler] Successfully resolved IP address, new address: http://172.31.0.4:9333/
2024-06-04T16:07:51.625Z error: [Crawler] Failed to connect to the browser instance, will retry in 5 secs
2024-06-04T16:07:56.627Z info: [Crawler] Connecting to existing browser instance: http://chrome:9333
2024-06-04T16:07:56.628Z info: [Crawler] Successfully resolved IP address, new address: http://172.31.0.4:9333/
2024-06-04T16:07:58.200Z error: [Crawler] Failed to connect to the browser instance, will retry in 5 secs

Chrome:
[0604/160227.059822:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[0604/160227.060817:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[0604/160227.060883:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[0604/160227.088938:WARNING:sandbox_linux.cc(420)] InitializeSandbox() called with multiple threads in process gpu-process.
[0604/160227.098655:INFO:config_dir_policy_loader.cc(118)] Skipping mandatory platform policies because no policy file was found at: /etc/chromium/policies/managed
[0604/160227.098690:INFO:config_dir_policy_loader.cc(118)] Skipping recommended platform policies because no policy file was found at: /etc/chromium/policies/recommended
[0604/160227.102479:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
DevTools listening on ws://0.0.0.0:9333/devtools/browser/6fe21986-5c5d-4c77-8acc-5deeed0aa8b9
Docker-compose
```yaml
version: "3.8"
services:
  web:
    image: ghcr.io/hoarder-app/hoarder-web:${HOARDER_VERSION:-release}
    container_name: hoarder-web
    restart: unless-stopped
    volumes:
      - ./web_data:/data
    ports:
      - 9025:3000
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      MEILI_ADDR: http://meilisearch:7700
      DATA_DIR: /data
  redis:
    container_name: hoarder-redis
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - ./redis:/data
  chrome:
    container_name: hoarder-chrome
    image: gcr.io/zenika-hub/alpine-chrome:124
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9333
      - --hide-scrollbars
  meilisearch:
    container_name: hoarder-meilisearch
    image: getmeili/meilisearch:v1.6
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - ./meilisearch:/meili_data
  workers:
    container_name: hoarder-workers
    image: ghcr.io/hoarder-app/hoarder-workers:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - ./web_data:/data
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9333
      DATA_DIR: /data
    depends_on:
      web:
        condition: service_started

```
