### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by spicman** [hoarder-app/hoarder#365]
First off, this is a great app, I use it all the time.  Unfortunately, the extension for the browser is not working for me.  Is it strictly for Chrome or can Edge use it (as well since they use the same base).  I keep getting Failed to fetch and that is even if I click Login without entering email/password:

![failedtofetch](https://github.com/user-attachments/assets/56d9f811-679a-4990-bbfb-3c57acdc4656)

On the phone different error:

![phone](https://github.com/user-attachments/assets/74206414-a292-4ca5-8c47-5cb0108d5a92)

I have several apps all working behind a traefik proxy, minus this one that is giving me issues.

I can't seem to find logs to help out the matter.

Regards,

Marcelo

**Comment by firestrife23** [comment]
Came here looking for an answer... same issue as yours.

**Comment by spicman** [comment]
Unfortunately, no one else but you and I are getting this? I can't see any errors in the log either.  

Other than this issue the app works great and I use it daily.

**Comment by firestrife23** [comment]
I figured it out. The issue is with my strict security header, and I had to loosen it up a little. Here's the one that worked for hoarder. The configuration below is for HTTP middleware.

```
    security-headers:
      headers:
        customResponseHeaders:
          X-Forwarded-Proto: "https"
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
          server: ""
        sslProxyHeaders:
          X-Forwarded-Proto: https
        referrerPolicy: "same-origin"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        stsPreload: true
```

**Comment by kamtschatka** [comment]
is this solved now?

**Comment by spicman** [comment]
Yes its solved for me now as well.  Similar to what firestrife23 posted.

Thanks!

**Comment by dominic248** [comment]
Hi @firestrife23 and @spicman ,
Could you please let me know in which section of the Docker yaml we should place the security-headers configuration? 
I have hosted `hoarder` on my Synology NAS, but I'm encountering a "Failed to fetch" error when attempting to login in the Chrome extension.

Thank you!

**Comment by berilslv** [comment]
> Hi @firestrife23 and @spicman , Could you please let me know in which section of the Docker yaml we should place the security-headers configuration? I have hosted `hoarder` on my Synology NAS, but I'm encountering a "Failed to fetch" error when attempting to login in the Chrome extension.
> 
> Thank you!

Hi guys,
bumping this up!
Im looking for solution for hoarder plugin , if hoarder docker container is provisioned behind NPM (nginx proxy manager)
Im getting same error: failed to fetch

BR,
Berils.

**Comment by dominic248** [comment]
Hi @berilslv 
After adding `http://` as prefix the issue got resolved.
Please try adding `http://` or `https://` as prefix and see if it works
Using IP address / domain name without http/https will result in "Failed to fetch" error in this extension

Hi @firestrife23 
I didn't try that solution, because http/https prefix worked for me
Still Thank you so much for sharing the info!

**Comment by makp0** [comment]
Press "Inspect" on the extension window. And you'll be able to open console and see the actual error.

If anyone else suffers from the CORS problem: 
* get the origin of the extension from dev tools. Something like 'chrome-extension://kgcjekpmcjjogibpjebkhaanilehneje'
* put it into "Custom CORS Origin" or whatever your server has. I use https://github.com/azukaar/Cosmos-Server and it's a fix specific to it

**Comment by uberjew666** [comment]
> Just posting a solution to my problem. Press "Inspect" on the extension window. And you'll be able to open console and see the actual error.
> 
> If anyone else suffers from the CORS problem:
> 
> * get the origin of the extension from dev tools. Something like 'chrome-extension://kgcjekpmcjjogibpjebkhaanilehneje'
> * put it into "Custom CORS Origin" or whatever your server has. I use https://github.com/azukaar/Cosmos-Server and it's a fix specific to it

This worked for me. The following is the config for Traefik.

```yaml
http:
  middlewares:
    security:
      headers:
        accessControlAllowOriginList:
          - 'chrome-extension://kgcjekpmcjjogibpjebkhaanilehneje'
```
