### ISSUE TITLE
Docker Compose Up Not working

### ISSUE THREAD

**Issue by hassanraha** [hoarder-app/hoarder#510]
Hi folks,

I am trying to self host hoarder in my laptop. I was following the steps given here: https://docs.hoarder.app/Installation/docker/

But I am getting the following error when I run `docker compose up`

```
docker compose up --pull always -d
[+] Running 3/3
 ✘ chrome Error      context canceled                                                                                                                                                                                      1.9s 
 ✘ meilisearch Error context canceled                                                                                                                                                                                      1.9s 
 ✘ web Error         Head "https://ghcr.io/v2/hoarder-app/hoarder/manifests/release": denied: denied                                                                                                                       1.9s 
Error response from daemon: Head "https://ghcr.io/v2/hoarder-app/hoarder/manifests/release": denied: denied
```

What could be the issue? I tried hitting the URL of container but it still says unauthorized. Do I need to get cred from somewhere?

**Comment by MohamedBassem** [comment]
hmmm, that's weird. No you're not supposed to get creds from anywhere and it should have just worked.

**Comment by MohamedBassem** [comment]
Can you share your docker compose?

**Comment by hassanraha** [comment]
Below is the docker-compose.yml and I have set all my envs in `.env`
```yaml
version: "3.8"
services:
  web:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - data:/data
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      # OPENAI_API_KEY: ...
      DATA_DIR: /data
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.6
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data

volumes:
  meilisearch:
  data:
```
