### ISSUE TITLE
 [Crawler] Failed to connect to the browser instance, will retry in 5 secs

### ISSUE THREAD

**Issue by geosmart** [hoarder-app/hoarder#577]
### Describe the Bug

hoarder-web-1  | 2024-10-20T13:17:11.013Z info: Workers version: 0.18.0
hoarder-web-1  | 2024-10-20T13:17:11.032Z info: [Crawler] Connecting to existing browser instance: http://192.168.68.100:9222
hoarder-web-1  | 2024-10-20T13:17:11.033Z info: [Crawler] Successfully resolved IP address, new address: http://192.168.68.100:9222/
hoarder-web-1  | (node:140) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
hoarder-web-1  | (Use `node --trace-deprecation ...` to show where the warning was created)
hoarder-web-1  | 2024-10-20T13:17:12.714Z error: [Crawler] Failed to connect to the browser instance, will retry in 5 secs
hoarder-web-1  | 2024-10-20T13:17:12.715Z info: Starting crawler worker ...
hoarder-web-1  | 2024-10-20T13:17:12.716Z info: Starting inference worker ...
hoarder-web-1  | 2024-10-20T13:17:12.716Z info: Starting search indexing worker ...
hoarder-web-1  | 2024-10-20T13:17:12.717Z info: Starting tidy assets worker ...
hoarder-web-1  | 2024-10-20T13:17:17.716Z info: [Crawler] Connecting to existing browser instance: http://192.168.68.100:9222
hoarder-web-1  | 2024-10-20T13:17:17.717Z info: [Crawler] Successfully resolved IP address, new address: http://192.168.68.100:9222/
hoarder-web-1  | 2024-10-20T13:17:19.378Z error: [Crawler] Failed to connect to the browser instance, will retry in 5 secs
hoarder-web-1  | 2024-10-20T13:17:24.380Z info: [Crawler] Connecting to existing browser instance: http://192.168.68.100:9222
hoarder-web-1  | 2024-10-20T13:17:24.380Z info: [Crawler] Successfully resolved IP address, new address: http://192.168.68.100:9222/
hoarder-web-1  | 2024-10-20T13:17:25.947Z error: [Crawler] Failed to connect to the browser instance, will retry in 5 secs
hoarder-web-1  | 2024-10-20T13:17:30.948Z info: [Crawler] Connecting to existing browser instance: http://192.168.68.100:9222
hoarder-web-1  | 2024-10-20T13:17:30.948Z info: [Crawler] Successfully resolved IP address, new address: http://192.168.68.100:9222/
hoarder-web-1  | 2024-10-20T13:17:32.615Z error: [Crawler] Failed to connect to the browser instance, will retry in 5 secs
hoarder-web-1  | 2024-10-20T13:17:36.265Z info: [Crawler][4] Will crawl "https://docs.hoarder.app/configuration" for link with id "vrmnjh84tvaby79xbbsl6l1c"
hoarder-web-1  | 2024-10-20T13:17:36.265Z info: [Crawler][4] Attempting to determine the content-type for the url https://docs.hoarder.app/configuration
hoarder-web-1  | 2024-10-20T13:17:37.616Z info: [Crawler] Connecting to existing browser instance: http://192.168.68.100:9222
hoarder-web-1  | 2024-10-20T13:17:37.616Z info: [Crawler] Successfully resolved IP address, new address: http://192.168.68.100:9222/
hoarder-web-1  | 2024-10-20T13:17:39.223Z error: [Crawler] Failed to connect to the browser instance, will retry in 5 secs

### Steps to Reproduce

.env
```bash
HOARDER_VERSION=release
NEXTAUTH_SECRET=xxxxxx
MEILI_MASTER_KEY=IMBU2dG9d5I5s6
NEXTAUTH_URL=http://xxxxxx.duckdns.org:3000
```

```yml
version: "3.8"
services:
  web:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - /mnt/mind/data/hoarder/data:/data
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://192.168.68.100:17700
      BROWSER_WEB_URL: http://192.168.68.100:9222
      HTTPS_PRXY: http://192.168.68.100:1081
      DATA_DIR: /data
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    ports:
      - 9222:9222
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.6
    restart: unless-stopped
    ports:
      - 17700:7700
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - /mnt/mind/data/hoarder/meili:/meili_data
```

### Expected Behaviour

the host ip is 192.168.68.100
in web container,is fine
```bash
curl http://192.168.68.100:9222/json 
[  ]
```
why   [Crawler] Failed to connect to the browser instance, will retry in 5 secs

### Exact Hoarder Version

v0.18.0
