### ISSUE TITLE
Bookmarks on Homepage not showing up

### ISSUE THREAD

**Issue by DevGoran** [hoarder-app/hoarder#626]
### Describe the Bug

Out of nowhere I saw the "Something went wrong" message in the "Home" tab. However, when clicking on the tags in the Tags page, it will show me the bookmarks accordingly.

### Steps to Reproduce

Open hoarder

### Expected Behaviour

Bookmarks show up in home tab.

### Screenshots or Additional Context

Container Log shows following error:

```
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
Running db migration script
s6-rc: info: service init-db-migration successfully started
s6-rc: info: service svc-workers: starting
s6-rc: info: service svc-web: starting
s6-rc: info: service svc-web successfully started
s6-rc: info: service svc-workers successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
  ▲ Next.js 14.2.13
  - Local:        http://localhost:3000
  - Network:      http://0.0.0.0:3000
 ✓ Starting...
> @hoarder/workers@0.1.0 start:prod /app/apps/workers
> tsx index.ts
 ✓ Ready in 2s
2024-11-07T09:03:58.989Z info: Workers version: 0.18.0
2024-11-07T09:03:59.059Z info: [Crawler] Connecting to existing browser instance: http://chrome:9222
(node:121) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
2024-11-07T09:03:59.083Z info: [Crawler] Successfully resolved IP address, new address: http://172.25.0.4:9222/
2024-11-07T09:03:59.674Z info: Starting crawler worker ...
2024-11-07T09:03:59.675Z info: Starting inference worker ...
2024-11-07T09:03:59.675Z info: Starting search indexing worker ...
2024-11-07T09:03:59.676Z info: Starting tidy assets worker ...
s [TRPCError]: Output validation failed
    at p (/app/apps/web/.next/server/chunks/105.js:4:32422)
    at async a (/app/apps/web/.next/server/chunks/105.js:4:32960)
    ... 4 lines matching cause stack trace ...
    at async u (/app/apps/web/.next/server/app/dashboard/bookmarks/page.js:1:5511) {
  code: 'INTERNAL_SERVER_ERROR',
  digest: '3286899713',
  [cause]: o [ZodError]: [
    {
      "validation": "url",
      "code": "invalid_string",
      "message": "Invalid url",
      "path": [
        "bookmarks",
        0,
        "content",
        "imageUrl"
      ]
    }
  ]
      at get error (/app/apps/web/.next/server/chunks/109.js:58:14318)
      at Q.parseAsync (/app/apps/web/.next/server/chunks/109.js:58:16801)
      at async p (/app/apps/web/.next/server/chunks/105.js:4:32371)
      at async a (/app/apps/web/.next/server/chunks/105.js:4:32960)
      at async a (/app/apps/web/.next/server/chunks/105.js:4:32960)
      at async a (/app/apps/web/.next/server/chunks/105.js:4:32960)
      at async a (/app/apps/web/.next/server/chunks/105.js:4:32960)
      at async p (/app/apps/web/.next/server/chunks/105.js:4:33299)
      at async u (/app/apps/web/.next/server/app/dashboard/bookmarks/page.js:1:5511) {
    issues: [ [Object] ],
    addIssue: [Function (anonymous)],
    addIssues: [Function (anonymous)],
    errors: [ [Object] ]
  }
}
s [TRPCError]: Output validation failed
    at p (/app/apps/web/.next/server/chunks/105.js:4:32422)
    at async a (/app/apps/web/.next/server/chunks/105.js:4:32960)
    ... 4 lines matching cause stack trace ...
    at async u (/app/apps/web/.next/server/app/dashboard/bookmarks/page.js:1:5511) {
  code: 'INTERNAL_SERVER_ERROR',
  digest: '3286899713',
  [cause]: o [ZodError]: [
    {
      "validation": "url",
      "code": "invalid_string",
      "message": "Invalid url",
      "path": [
        "bookmarks",
        0,
        "content",
        "imageUrl"
      ]
    }
  ]
      at get error (/app/apps/web/.next/server/chunks/109.js:58:14318)
      at Q.parseAsync (/app/apps/web/.next/server/chunks/109.js:58:16801)
      at async p (/app/apps/web/.next/server/chunks/105.js:4:32371)
      at async a (/app/apps/web/.next/server/chunks/105.js:4:32960)
      at async a (/app/apps/web/.next/server/chunks/105.js:4:32960)
      at async a (/app/apps/web/.next/server/chunks/105.js:4:32960)
      at async a (/app/apps/web/.next/server/chunks/105.js:4:32960)
      at async p (/app/apps/web/.next/server/chunks/105.js:4:33299)
      at async u (/app/apps/web/.next/server/app/dashboard/bookmarks/page.js:1:5511) {
    issues: [ [Object] ],
    addIssue: [Function (anonymous)],
    addIssues: [Function (anonymous)],
    errors: [ [Object] ]
  }
}
```

Compose:

```
version: "3.8"
services:
  web:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - data:/data
    ports:
      - 3232:3000
    env_file:
      - stack.env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data
    dns: ip
    
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.6
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data

volumes:
  meilisearch:
  data:
```

### Exact Hoarder Version

v0.18.0
