### ISSUE TITLE
"no such table: tasks" when adding a new item

### ISSUE THREAD

**Issue by Azhelor** [hoarder-app/hoarder#666]
### Describe the Bug

Hi,

I just installed the last version of Hoarder (v 0.19.0) following the steps here : https://docs.hoarder.app/Installation/docker/ 

Installation, sign up and log in worked just fine but when I'm trying to add a new item from the home page, I get a red alert saying "no such table: tasks". But when I refresh the page, the item appears.

By the way, I got a similar mistake when trying to delete an item, with a red alert bow saying "Something went wrong. There was a problem with your request." Mention that because I assume both errors could be linked.

I found another bug report with the same error and found out that my queue.db is also empty this might come from a database migration error, but I have no idea how to fix that since I'm pretty new to all of this.

Thanks for your help.

### Steps to Reproduce

1. Install a brand new Hoarder with docker compose
2. Create user and log in
3. Try to add a new item

### Expected Behaviour

I guess item should be immediately added and visible and no error should be shown.

### Exact Hoarder Version

v0.19.0

**Comment by MohamedBassem** [comment]
Hey, can you try deleting `queue.db` and restarting the container? That should recreate it

**Comment by Azhelor** [comment]
Hi, thanks for your answer. I tried that fix, but unfortunately it did not work. queue.db was indeed recreated but is still empty. Don't know if it's important, but the database was not recreated during container restart but after I tried to add a new item.

**Comment by stayupthetree** [comment]
I am getting this error as well on a fresh install. I tried the removal of queue.db and result is the same

**Comment by MohamedBassem** [comment]
hmmm, that's unexpected. The `queue.db` file should be created on container startup. Can you share the logs immediately after starting the container?

**Comment by MohamedBassem** [comment]
Can you also share your compose file and redacted env file?

**Comment by Azhelor** [comment]
Sure. I deleted queue.db once again and here are the logs of "hoarder-web-1" and "hoarder-chrome-1" (I don't know which one is relevant here).

hoarder-web-1:
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service init-db-migration: starting
Running db migration script
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-db-migration successfully started
s6-rc: info: service svc-workers: starting
s6-rc: info: service svc-web: starting
s6-rc: info: service svc-workers successfully started
s6-rc: info: service svc-web successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
  ▲ Next.js 14.2.13
  - Local:        http://localhost:3000
  - Network:      http://0.0.0.0:3000

 ✓ Starting...
 ✓ Ready in 403ms
```

hoarder-chrome-1:
```
[1118/212522.742137:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[1118/212522.743160:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[1118/212522.743311:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[1118/212522.743528:WARNING:dns_config_service_linux.cc(427)] Failed to read DnsConfig.
[1118/212522.755910:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping mandatory platform policies because no policy file was found at: /etc/chromium/policies/managed
[1118/212522.755935:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping recommended platform policies because no policy file was found at: /etc/chromium/policies/recommended

DevTools listening on ws://0.0.0.0:9222/devtools/browser/bdfa091e-772d-4305-ac47-65a31c16276c
[1118/212522.760146:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
[1118/212522.781625:WARNING:sandbox_linux.cc(418)] InitializeSandbox() called with multiple threads in process gpu-process.
[1118/212522.845023:WARNING:dns_config_service_linux.cc(427)] Failed to read DnsConfig.
```

Once again, I don't if it's important, but a few seconds after restart I get this error several times in hoarder-web-1 container:
```
/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21609
    throw new Error(
          ^

Error: Error when performing the request to https://registry.npmjs.org/pnpm/latest; for troubleshooting help, see https://github.com/nodejs/corepack#troubleshooting
    at fetch (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21609:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async fetchAsJson (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21623:20)
    ... 4 lines matching cause stack trace ...
    at async Object.runMain (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:23096:5) {
  [cause]: TypeError: fetch failed
      at node:internal/deps/undici/undici:13392:13
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async fetch (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21603:16)
      at async fetchAsJson (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21623:20)
      at async fetchLatestStableVersion (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21550:20)
      at async fetchLatestStableVersion2 (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21672:14)
      at async Engine.getDefaultVersion (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:22292:23)
      at async Engine.executePackageManagerRequest (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:22390:47)
      at async Object.runMain (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:23096:5) {
    [cause]: Error: getaddrinfo EAI_AGAIN registry.npmjs.org
        at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
      errno: -3001,
      code: 'EAI_AGAIN',
      syscall: 'getaddrinfo',
      hostname: 'registry.npmjs.org'
    }
  }
}

Node.js v22.11.0
```

Here is docker-compose.yml (I didn't change anything from the file linked in installation doc):
```
version: "3.8"
services:
  web:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - data:/data
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      # OPENAI_API_KEY: ...
      DATA_DIR: /data
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data

volumes:
  meilisearch:
  data:
```

And here is .env (I just removed next url and both secret keys):
```
HOARDER_VERSION=release
NEXTAUTH_SECRET=#secret1
MEILI_MASTER_KEY=#secret2
NEXTAUTH_URL=#nexturl
```

At that time, container is restarted since a few minutes, I did not try to connect to hoarder and queue.db is still missing in data repository.
