### ISSUE TITLE
Failed to connect to the browser instance, will retry in 5 secs

### ISSUE THREAD

**Issue by snowdream** [hoarder-app/hoarder#674]
### Describe the Bug

https://docs.hoarder.app/Installation/docker

i try to run hoarder with docker compose,but failed.

<img width="1270" alt="image" src="https://github.com/user-attachments/assets/b4518c99-2e0e-454d-b571-04386f81e8af">
<img width="1270" alt="image" src="https://github.com/user-attachments/assets/0e158613-d444-4787-9a26-ba4b41cbc2b9">
<img width="1270" alt="image" src="https://github.com/user-attachments/assets/3b5107c0-6fe8-41f8-a99c-03afa3af99da">
<img width="1270" alt="image" src="https://github.com/user-attachments/assets/9a5a73db-5f91-4b1a-ba76-b28fc740dd6b">

### Steps to Reproduce

1. create .env
```
HOARDER_VERSION=release
NEXTAUTH_SECRET=super_random_string
MEILI_MASTER_KEY=another_random_string
NEXTAUTH_URL=http://localhost:3000
```

2. create docker-compose.yml
```
version: "3.8"
services:
  web:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - data:/data
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      # OPENAI_API_KEY: ...
      DATA_DIR: /data
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data

volumes:
  meilisearch:
  data:
```

3. docker compose up -d
```
docker compose up -d
```

### Expected Behaviour

http://localhost:3000/  is OK

### Screenshots or Additional Context

<img width="1439" alt="image" src="https://github.com/user-attachments/assets/67dec34d-892c-4f0b-b070-f3be9d19b378">

### Device Details

Microsoft Edge 版本 131.0.2903.48 (正式版本) (x86_64)  On macOS

### Exact Hoarder Version

release
