### ISSUE TITLE
Add healthchecks for all the containers

### ISSUE THREAD

**Issue by r4nchy** [hoarder-app/hoarder#696]
### Describe the feature you'd like

I wish that hoarder should have a standard [container healthcheck](https://docs.docker.com/reference/compose-file/services/#healthcheck) in the docker container.

I helps in monitoring docker containers

![](https://i.imgur.com/PQteBpj.png)

### Describe the benefits this would bring to existing Hoarder users

This would make troubleshooting easy as to which container is healthy or unhealthy.

### Can the goal of this request already be achieved via other means?

It was achievable using the following in the compose file, but doesn't seem to work anymore. and few other hoarder containers don't have healthchecks as well

```
    healthcheck:
      test: ["CMD-SHELL", "ss -lnt | grep ':3000' || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
      ```

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request
