### ISSUE TITLE
Scrollbar not working for long notes

### ISSUE THREAD

**Issue by esteve88** [hoarder-app/hoarder#793]
### Describe the Bug

When I'm opening the preview of a note from the main screen (using the expand button ![image](https://github.com/user-attachments/assets/aff9aa7b-3149-4eca-ac09-5199cdb13ade) ), in case of a long note, the note is not completely displayed and the scrollbar is neither displayed nor it is working. 
If I refresh the screen, then the note and the scrollbar are both visualized.
This is happening on both Chrome and Edge (on Windows), as well as on Safari (from iOS).

I'm using the latest Hoarder version (0.20.0) installed through Docker. I'm also copying here below my docker compose:

```
version: "3.8"
services:
  web:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - /data/docker/hoarder/hoarder-data:/data
    ports:
      - 3123:3000
    #env_file:
    #  - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      OPENAI_API_KEY: <redacted>
      DATA_DIR: /data
      HOARDER_VERSION: release
      NEXTAUTH_SECRET: <redacted>
      NEXTAUTH_URL: http://192.168.1.102:3123
      MEILI_MASTER_KEY: <redacted>
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    restart: unless-stopped
    #env_file:
    #  - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
      HOARDER_VERSION: release
      NEXTAUTH_SECRET: <redacted>
      NEXTAUTH_URL: http://192.168.1.102:3123
      MEILI_MASTER_KEY: <redacted>
    volumes:
      - /data/docker/hoarder/meili-data:/meili_data
``` 

### Steps to Reproduce

1. Create a very long note
2. Open the related preview using the arrows button

### Expected Behaviour

The note is opened and scrollbars are shown (and working)

### Screenshots or Additional Context

Screenshot of the note preview when it is opened (and scrollbars are not shown and not working):

![image](https://github.com/user-attachments/assets/3c3a41cd-22e3-4e64-9066-d9213705785f)

Screenshot of the note after the browser has been refreshed (scrollbars are shown and are working):

![image](https://github.com/user-attachments/assets/23ab371a-88dc-45de-a8f2-d6360eda5b40)

### Device Details

Chrome, Edge, Safari (iOS)

### Exact Hoarder Version

v0.20.0

### Have you checked the troubleshooting guide?

- [X] I have checked the troubleshooting guide and I haven't found a solution to my problem
