### ISSUE TITLE
No data in DATA_DIR

### ISSUE THREAD

**Issue by Pietro395** [hoarder-app/hoarder#803]
### Describe the Bug

I am using the docker compose file as explained in the documentation and have populated the .env file with the DATA_DIR parameter but no data is present in the specified folder.

.env:
```
HOARDER_VERSION=release
DATA_DIR=/data
NEXTAUTH_SECRET=<redacted>
MEILI_MASTER_KEY=<redacted>
NEXTAUTH_URL=https://hoarder.xx.x
OPENAI_API_KEY=<redacted>
OPENAI_BASE_URL=https://openrouter.ai/api/v1/
DISABLE_SIGNUPS=true
```

docker-compose.yml:
```
version: "3.8"
services:
  web:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - data:/data
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      # OPENAI_API_KEY: ...
      DATA_DIR: /data
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data

volumes:
  meilisearch:
  data:
```

### Steps to Reproduce

1. Download docker-compose.yml 
2. Populate .env
3. Run container
4. No data in DATA_DIR

### Expected Behaviour

I find files in the folder specified in DATA_DIR

### Exact Hoarder Version

0.20.0

### Have you checked the troubleshooting guide?

- [X] I have checked the troubleshooting guide and I haven't found a solution to my problem
