### ISSUE TITLE
Queue in stuck state?

### ISSUE THREAD

**Issue by icco** [hoarder-app/hoarder#832]
### Describe the Bug

I uploaded around 100k bookmarks to hoarder, and it seems like the queue hasn't progressed in the last few days. Is there a process for resetting or debugging the queue?

### Steps to Reproduce

N/A

### Expected Behaviour

Some sort of logging from container about queue and how it's progressing or if it's running into errors.

### Screenshots or Additional Context

<img width="1409" alt="Screenshot 2025-01-05 at 12 39 55" src="https://github.com/user-attachments/assets/f52e2336-5002-47e7-95ef-1d3a3ff216e0" />

### Device Details

docker

### Exact Hoarder Version

v0.21.0

### Have you checked the troubleshooting guide?

- [X] I have checked the troubleshooting guide and I haven't found a solution to my problem

**Comment by MohamedBassem** [comment]
We log extensively actually every time a worker picks up/completes a queued job. Are you not seeing any logs from the container at all? Can you try restarting the container and sharing the logs that you see on startup?

**Comment by icco** [comment]
<img width="1822" alt="Screenshot 2025-01-05 at 12 45 20" src="https://github.com/user-attachments/assets/57f7e6b6-7ee8-4859-811a-eb43488c3c20" />

**Comment by icco** [comment]
Docker Compose config:

```
  hoarder:
    image: ghcr.io/hoarder-app/hoarder:release
    restart: unless-stopped
    environment:
      BROWSER_WEB_URL: http://chrome:9222
      CRAWLER_FULL_PAGE_ARCHIVE: true
      CRAWLER_NUM_WORKERS: 2
      DATA_DIR: /data
      DISABLE_SIGNUPS: true
      LOG_LEVEL: debug
      MEILI_ADDR: http://meilisearch:7700
      MEILI_MASTER_KEY: HIDDEN
      NEXTAUTH_SECRET: HIDDEN
      NEXTAUTH_URL: https://hoard.natwelch.com
      OPENAI_API_KEY: HIDDEN
    volumes:
      - /docker/appdata/hoarder:/data
    labels:
      prometheus.io/scrape: false
      caddy: hoard.natwelch.com
      caddy.reverse_proxy: '{{upstreams 3000}}'
      caddy.log:
    networks:
      - caddy
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:latest
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    labels:
      prometheus.io/scrape: false
    networks:
      - caddy
  meilisearch:
    image: getmeili/meilisearch:latest
    restart: unless-stopped
    environment:
      MEILI_MASTER_KEY: HIDDEN
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - /docker/appdata/meilisearch:/meili_data
    labels:
      prometheus.io/scrape: false
    networks:
      - caddy
```
