### ISSUE TITLE
Several issues when trying to run hoarder

### ISSUE THREAD

**Issue by schumi2004** [hoarder-app/hoarder#897]
### Describe the Bug

I really love the idea about hoarder but i just can't get it working.

I have several issues.
During my first run i could register and connect to Hoarder without issues except when i tried to connect via reverse proxy (traefik / gateway timeout)
As mentioned in other issue i already had label "traefik.docker.network=proxy" present like i have for all my other endpoints that are working perfectly.

Then i played with the provided docker compose, added all the required fields, wiped all images, volumes networks etc and started from scratch.
Now i can register but not login (directly redirected to login again.
Still the reverse proxy entry is not working.

Tried several things but i just can't get it to work.

Also have a error from the very first setup for chrome, all other containers don't seem to have any errors:

`[0117/085007.682424:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[0117/085007.682112:WARNING:dns_config_service_linux.cc(427)] Failed to read DnsConfig.
[0117/085007.683538:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[0117/085007.683752:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[0117/085007.888914:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping mandatory platform policies because no policy file was found at: /etc/chromium/policies/managed
[0117/085007.888952:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping recommended platform policies because no policy file was found at: /etc/chromium/policies/recommended
[0117/085007.944294:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
DevTools listening on ws://0.0.0.0:9222/devtools/browser/99b4b4ad-a9c2-43fd-aee3-3c3dffa86acd
[0117/085008.074112:WARNING:sandbox_linux.cc(418)] InitializeSandbox() called with multiple threads in process gpu-process.
[0117/085008.346355:WARNING:dns_config_service_linux.cc(427)] Failed to read DnsConfig.`

This is my docker-compose.yml

```
services:
  hoarder:
    image: ghcr.io/hoarder-app/hoarder:latest
    container_name: hoarder
    restart: unless-stopped
    volumes:
      - hoarder:/data
    ports:
      - 4000:3000
    env_file:
      - .env
    networks:
      - proxy
      - backend
    environment:
      #DISABLE_SIGNUPS: true
      MEILI_ADDR: http://meilisearch:7700
      MEILI_MASTER_KEY: <some secret>
      BROWSER_WEB_URL: http://chrome:9222
      NEXTAUTH_URL: https://hoarder.local.domain.tld
      NEXTAUTH_SECRET: <some secret>
      # OPENAI_API_KEY: ...
      DATA_DIR: /data
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    container_name: chrome
    restart: unless-stopped
    networks:
      - backend
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    container_name: meilisearch
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - backend
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data

    labels:
    # Traefik config
      - "traefik.enable=true"
      - "traefik.http.routers.hoarder.entrypoints=https"
      - "traefik.http.routers.hoarder.rule=Host(`hoarder.local.domain.tld`)"
      - "traefik.http.routers.hoarder.tls=true"
      - "traefik.http.routers.hoarder.service=hoarder"
      - "traefik.http.routers.hoarder.middlewares=internal@file"
      - "traefik.http.services.hoarder.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"

volumes:
  meilisearch:
  hoarder:

networks:
  proxy:
    external: true
  backend:
    external: true
```

Currently i'm out of ideas and have no idea how to proceed.

### Steps to Reproduce

Setup using provided docker-compose.yml and fill in all the required fields

### Expected Behaviour

Register and be able to login.
Access hoarder via reverse proxy without issues

### Exact Hoarder Version

latest

### Have you checked the troubleshooting guide?

- [x] I have checked the troubleshooting guide and I haven't found a solution to my problem
