### ISSUE TITLE
[Feature request] NextAuth Providers for OAuth/SSO

### ISSUE THREAD

**Issue by schmoaaaaah** [hoarder-app/hoarder#92]
The ability to use the [NextAuth Providers](https://next-auth.js.org/providers/) for OAuth Authentication would be nice.

**Comment by linedpaper** [comment]
Agreed, any sort of external would be great!

**Comment by kamtschatka** [comment]
which providers would be most interesting? there are 60+ proviers, that is a bit much ;-)

**Comment by MohamedBassem** [comment]
@kamtschatka I'd add only the generic oauth one

**Comment by Schmoaaaaah** [comment]
You could also do it with big ENV vars:
```yaml
providers: |
  AuthentikProvider({
    clientId: process.env.AUTHENTIK_ID,
    clientSecret: process.env.AUTHENTIK_SECRET,
    issuer: process.env.AUTHENTIK_ISSUER,
  })
```
and add them to the provideres array in Nextauth, but I agree the Generic Oauth would be easier to implement.
