### ISSUE TITLE
Chrome at 85% CPU

### ISSUE THREAD

**Issue by stanthewizzard** [hoarder-app/hoarder#960]
### Describe the Bug

Everything is working fine
I have 10 tiles

But chrome is eating the CPU 

Thanks for help

### Steps to Reproduce

Docker compose

```
services:
  web:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    container_name: hoarder-app
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 34732:3000
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      # OPENAI_API_KEY: ...
      DATA_DIR: /data
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    container_name: hoarder-app_chrome

    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    restart: unless-stopped
    container_name: hoarder-app_meilisearch
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - ./meilisearch:/meili_data
```

.env

```
# See https://docs.hoarder.app/configuration for more information
DATA_DIR=/data
MEILI_ADDR=http://127.0.0.1:7700
MEILI_MASTER_KEY=xxxxxxxxxxxxxxxxxxxxxxxx
NEXTAUTH_URL=https://hoarderapp.xxxxxx.com/
NEXTAUTH_SECRET=xxxxxxxxxxxxxxxxxx
OLLAMA_BASE_URL=http://192.168.0.198:11434
INFERENCE_TEXT_MODEL=phi4:latest
INFERENCE_IMAGE_MODEL=llava
EMBEDDING_TEXT_MODEL=phi4:latest
```

### Expected Behaviour

Not that much CPU

### Screenshots or Additional Context

hoarder-app_chrome | running | 14 mins | **84,3** | 616M | 9.71G

### Exact Hoarder Version

0.21.0

### Have you checked the troubleshooting guide?

- [x] I have checked the troubleshooting guide and I haven't found a solution to my problem
